server:
    port: 80

spring:
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

swaggerhost: dbhomework.backend.117503445.top
app:
    version: @project.version@
    build:
        time: @timestamp@